---
title: "Practice Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(ggplot2)
library(flexdashboard)
library(Lahman)
library(sqldf)
library(devtools)
library(blogdown)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Salaries

```{r}
#extracting the data----------
query<-"SELECT salary
FROM Salaries"
result<-sqldf(query)

#visualizing the data--------
ggplot()+
  geom_histogram(data=result,aes(x=salary),color="blue",fill="white",bins=50)+
  ggtitle("Salaries")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Average Salary per Year

```{r}
#extracting the data----------
query<-"SELECT yearID,avg(salary) AS avg_salary
FROM Salaries
GROUP BY yearID"
result<-sqldf(query)

#visualizing the data--------
ggplot()+
  geom_line(data=result,aes(x=yearID,y=avg_salary))
```

### Salaries and Homeruns

```{r}
#extracting the data----------
query<-"SELECT Batting.playerID,HR,salary 
FROM Batting INNER JOIN Salaries
ON Batting.playerID=Salaries.playerID 
WHERE HR>=10"
result<-sqldf(query)


#visualizing the data--------
ggplot()+
  geom_point(data=result,aes(x=salary,y=HR))+
  ggtitle("Salary VS Homeruns")+
  xlab("Salary")+
  ylab("Homeruns")
```


